phases:
- phase: Windows
  queue:
    name: Hosted VS2017
    timeoutInMinutes: 90
    parallel: 4
    matrix:
      Samples Debug:
        _command: eng\PRBuild.cmd
        _args: -configuration debug -prepareMachine -projects $(Build.SourcesDirectory)\Samples.sln
        _configuration: Debug
        _solution: Samples
      Samples Release:
        _command: eng\PRBuild.cmd
        _args: -configuration release -prepareMachine -projects $(Build.SourcesDirectory)\Samples.sln
        _configuration: Release
        _solution: Samples
      SDK Debug:
        _command: eng\PRBuild.cmd
        _args: -configuration debug -prepareMachine -projects $(Build.SourcesDirectory)\Roslyn-SDK.sln
        _configuration: Debug
        _solution: SDK
      SDK Release:
        _command: eeng\PRBuild.cmd
        _args: -configuration release -prepareMachine -projects $(Build.SourcesDirectory)\Roslyn-SDK.sln
        _configuration: Release
        _solution: SDK
  steps:
    - script: $(_command) $(_args)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts\$(_configuration)\log'
        ArtifactName: '$(_solution) $(_configuration) logs'
        publishLocation: Container
      continueOnError: true
      condition: failed()
    - task: PublishTestResults@2
      inputs:
        testRunner: 'xUnit'
        testResultsFiles: '**/*.xml' 
        searchFolder: '$(Build.SourcesDirectory)\artifacts\$(_configuration)\TestResults'
        configuration: '$(_configuration)'
        publishRunAttachments: true
      continueOnError: true