phases:
- phase: Windows
  queue:
    name: Hosted VS2017
    timeoutInMinutes: 90
    parallel: 4
    matrix:
      Samples Debug:
        _configuration: Debug
        _solution: Samples
      Samples Release:
        _configuration: Release
        _solution: Samples
      SDK Debug:
        _configuration: Debug
        _solution: Roslyn-SDK
      SDK Release:
        _configuration: Release
        _solution: Roslyn-SDK
  steps:
    - script: eng\PRBuild.cmd -configuration $(_configuration) -prepareMachine -projects $(Build.SourcesDirectory)\$(_solution).sln
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts\$(_configuration)\log'
        ArtifactName: '$(_solution) $(_configuration) logs'
        publishLocation: Container
      continueOnError: true
      condition: failed()
    - task: PublishTestResults@2
      inputs:
        testRunner: 'xUnit'
        testResultsFiles: '**/*.xml' 
        searchFolder: '$(Build.SourcesDirectory)\artifacts\$(_configuration)\TestResults'
        configuration: '$(_configuration)'
        publishRunAttachments: true
      continueOnError: true
      condition: always()